"""added current_place

Revision ID: c44b121f9e85
Revises: d4545ead4b04
Create Date: 2022-04-23 14:38:31.260447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c44b121f9e85'
down_revision = 'd4545ead4b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_place', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_place')
    # ### end Alembic commands ###
